### PR TITLE
Address deprecation of the Control.Newtype module

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by conal** [comment]
Thanks for the contribution!

How did you choose `>= 0.5.3` for newtype-generics?

**Comment by conal** [comment]
[Released to Hackage.](http://hackage.haskell.org/package/MemoTrie-0.6.10)

**Comment by sjakobi** [comment]
Thanks for the release! :)

> How did you choose `>= 0.5.3` for newtype-generics?

Earlier versions don't have the `Control.Newtype.Generics` module. That module was added to prevent clashes with the `Control.Newtype` module from the old `newtype` package.

**Comment by conal** [comment]
> Earlier versions don't have the `Control.Newtype.Generics` module. That module was added to prevent clashes with the `Control.Newtype` module from the old `newtype` package.

Got it. Thanks! I'm glad to know, as I have some other packages to update similarly.

**Pull request merged**
